.Dd $Mdocdate$
.Dt SUXML 1
.Os SUXML man page
.Th SUXML 15/05/2016
.Sh NAME
.Nm suxml
.Nd simple and opinionated XML editor

.Sh SYNOPSIS
.Nm suxml
.Op Fl -light
.Ar file
.Sh DESCRIPTION
.Nm
is a simple yet usable, opinionated XML editor.
Its arguments are as follows:
.Bl -tag -width Ds
.It Fl -light
Invert the color scheme into black on white text.
.It Ar file
The XML file to edit.
